# Generated by Django 4.1.5 on 2023-01-06 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_standard'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Standard',
        ),
    ]
